import Image from 'next/image';
import PresentationDeck from '@/components/PresentationDeck';
import presentations from '@/data/presentations.json';
import assets from '@/data/presentation-assets.json';
import resources from '@/data/resources.json';
import './e06.css';
const presentation = presentations.find((item) => item.slug === 'e06-espaco-aereo');
const allResources = Object.values(resources).flat();
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
export const metadata = { title: presentation.title, description: presentation.subtitle };
function Media({ assetId }) {
  const asset = assets.find((item) => item.id === assetId);
  return <figure className="air-media"><a href={basePath + asset.assetPath} target="_blank" rel="noreferrer" aria-label={`Abrir figura em tamanho original: ${asset.title}`}><Image src={basePath + asset.assetPath} alt={asset.alt} fill sizes="65vw" style={{ objectFit: 'contain' }} /></a><figcaption className="sr-only">{asset.creditLine}</figcaption></figure>;
}
function Slide({ kicker, title, source, minutes, notes, children, className = '' }) {
  return <section className={'air-slide ' + className}><header><div className="air-kicker">{kicker}</div><h2>{title}</h2></header><div className="air-body">{children}</div><aside className="notes">{'Tempo previsto: ' + minutes + ' minutos. ' + notes + ' Fonte: ' + source}</aside></section>;
}
function ReadingList({ ids }) {
  return <div className="air-downloads"><div>{ids.map(id => {
    const r = allResources.find(item => item.id === id);
    return <a key={id} href={basePath + r.assetPath} download><strong>{r.title}</strong><span>{r.authors.length > 3 ? r.authors[0] + ' et al.' : r.authors.join(' · ')} • {r.year}</span><b>Baixar PDF ↓</b></a>;
  })}</div><a className="air-library-link" href={basePath + '/biblioteca/espaco-aereo/'} target="_blank" rel="noreferrer">Abrir materiais da aula e créditos das figuras ↗</a></div>;
}
function AirspaceDiagram() {
  return <figure className="air-structure"><svg viewBox="0 0 760 550" role="img" aria-labelledby="airspace-title airspace-desc"><title id="airspace-title">Estruturas de espaço aéreo em corte vertical conceitual</title><desc id="airspace-desc">FIR envolve espaços controlados e não controlados. Uma CTA e uma TMA têm limites inferiores acima do terreno. A CTR parte da superfície. A ATZ protege o tráfego de aeródromo. Esquema sem escala e sem limites operacionais.</desc>
    <rect x="15" y="15" width="730" height="485" rx="14" fill="#e8f2f8" stroke="#71899e" strokeWidth="3" strokeDasharray="10 7"/>
    <text x="40" y="59" fontSize="26" fontWeight="800" fill="#0b3450">FIR • informação de voo e alerta</text>
    <rect x="60" y="95" width="640" height="120" rx="10" fill="#bce7ef" stroke="#0e7490" strokeWidth="3"/>
    <text x="380" y="145" textAnchor="middle" fontSize="32" fontWeight="800" fill="#0b3450">CTA</text><text x="380" y="181" textAnchor="middle" fontSize="23" fill="#0b3450">área de controle</text>
    <path d="M 105 245 H 660 V 342 H 540 V 390 H 225 V 342 H 105 Z" fill="#b4d4e8" stroke="#256287" strokeWidth="3"/>
    <text x="380" y="292" textAnchor="middle" fontSize="32" fontWeight="800" fill="#0b3450">TMA</text><text x="380" y="325" textAnchor="middle" fontSize="23" fill="#0b3450">área de controle terminal</text>
    <rect x="270" y="362" width="225" height="119" fill="#67c7d4" stroke="#0e7490" strokeWidth="3"/><text x="382" y="403" textAnchor="middle" fontSize="29" fontWeight="800" fill="#0b3450">CTR</text>
    <path d="M 307 480 V 457 Q 382 412 458 457 V 480 Z" fill="#fff" stroke="#385469" strokeWidth="2"/><text x="383" y="467" textAnchor="middle" fontSize="24" fontWeight="800" fill="#0b3450">ATZ</text>
    <path d="M 15 482 H 745" stroke="#8f7653" strokeWidth="6"/><text x="382" y="536" textAnchor="middle" fontSize="22" fill="#526579">Esquema conceitual • limites variam em cada local</text>
  </svg></figure>;
}
export default function E06PresentationPage() {
  return <PresentationDeck title={presentation.title} width={1600} height={900} className="air-deck">
<Slide kicker="IT-214 • Espaço aéreo" title="Espaço aéreo: estrutura, operação e integração" minutes={3} source="ICA 100-37; FAA UAM ConOps 2.0." notes="Abra com a pergunta: como incluir novos voos sem perder segurança e capacidade? A aula parte da organização atual do espaço aéreo, compara propostas e examina evidências de pesquisa. SIGMA-Sky é uma aplicação local, não o objeto da aula." className="air-title-slide">
<div className="air-cover"><div><p className="air-lead">Como organizar o espaço e coordenar quem voa nele?</p><p>Estrutura atual • regras e serviços • literatura • integração da mobilidade aérea urbana</p><div className="air-cover-meta">IT-214 • 08/09/2026<br/>Do sistema existente às operações UAM</div></div><Media assetId="faa-2023-uam-corridor-concept" /></div>
</Slide>
<Slide kicker="Percurso da aula" title="Quatro perguntas para ler qualquer proposta" minutes={3} source="Síntese didática." notes="Apresente o percurso e a atividade final. Pergunte o que cada estudante associa a espaço aéreo: volume, carta, regra ou controlador. Use respostas para mostrar que as quatro dimensões se complementam.">
<div className="air-bands"><article><h3>Como o espaço é organizado?</h3><p>FIR, áreas e zonas de controle, classes ATS, rotas e restrições.</p></article><article><h3>Como uma operação funciona?</h3><p>Regras de voo, informação, autorização, separação e coordenação entre órgãos.</p></article><article><h3>O que muda com a UAM?</h3><p>Novos fluxos, desempenho heterogêneo, serviços digitais e disputa por capacidade.</p></article><article><h3>Como avaliar uma solução?</h3><p>Comparar alternativas sob a mesma demanda e observar segurança, atraso e robustez.</p></article></div>
</Slide>
<Slide kicker="01 • Estrutura atual" title="FIR, TMA e CTR descrevem funções diferentes" minutes={6} source="ICA 100-37, arts. 18–20 e definições do Anexo VII." notes="A FIR delimita a prestação de informação de voo e alerta. Dentro dela há espaços controlados e não controlados. CTA começa acima de um limite sobre o terreno; a TMA é uma área de controle terminal. CTR se estende desde a superfície até um limite superior. ATZ protege o tráfego de aeródromo. O desenho é conceitual: dimensões e sobreposições variam. Não apresentar CTR como necessariamente dentro de uma TMA.">
<div className="air-evidence"><AirspaceDiagram /><div className="air-reading"><article><h3>FIR • informação de voo</h3><p>Região na qual são prestados informação de voo e alerta; pode conter espaços controlados.</p></article><article><h3>CTA / TMA • áreas de controle</h3><p>CTA organiza espaço controlado acima de um limite inferior. TMA atende à convergência de rotas junto a aeroportos.</p></article><article><h3>CTR / ATZ • proximidade do aeródromo</h3><p>CTR parte da superfície; ATZ protege o tráfego de aeródromo. Seus limites são publicados.</p></article></div></div>
</Slide>
<Slide kicker="01 • Classes ATS" title="A classe define quem recebe qual serviço" minutes={6} source="ICA 100-37, art. 21 e Anexo II." notes="Percorra C e D com um par IFR/VFR. Em C esse par recebe separação ATC; em D há informação de tráfego, e IFR é separado de IFR. B separa todos; A admite somente IFR. F é classe de assessoramento prevista no modelo. A tabela destaca C/D/E/G e não substitui requisitos completos de comunicação, velocidade e autorização. A designação de uma CTR não basta para inferir sua classe.">
<div className="air-table-wrap"><table><thead><tr><th>Classe</th><th>Separação ATC</th><th>O que observar</th></tr></thead><tbody><tr><td>C</td><td>IFR–IFR e IFR–VFR</td><td>VFR–VFR recebe informação de tráfego.</td></tr><tr><td>D</td><td>IFR–IFR</td><td>IFR e VFR recebem ATC, mas informação de tráfego não equivale à separação de todos os pares.</td></tr><tr><td>E</td><td>IFR–IFR</td><td>ATC para IFR; informação de tráfego, quando possível, para os demais encontros.</td></tr><tr><td>G</td><td>Sem separação ATC</td><td>Informação de voo quando possível e solicitada; responsabilidades do piloto permanecem.</td></tr></tbody></table></div>
</Slide>
<Slide kicker="01 • Regras e meteorologia" title="Regra de voo e condição meteorológica são dimensões distintas" minutes={5} source="ICA 100-12, capítulos IV e V; ICA 100-37, art. 21." notes="Não simplifique IFR como mau tempo e VFR como ausência de controle. IFR pode ocorrer em condições visuais; VFR pode operar em espaço controlado. Serviços e responsabilidade por separação dependem da classe e do tipo de operação. Pergunte: um eVTOL elétrico ganha uma regra de voo própria? Não pela propulsão.">
<div className="air-table-wrap"><table><thead><tr><th>Dimensão</th><th>O que define</th><th>Exemplo para a integração</th></tr></thead><tbody><tr><td>VFR / IFR</td><td>Regras de condução do voo</td><td>Escolher operação compatível com aeronave, piloto, procedimentos e ambiente.</td></tr><tr><td>VMC / IMC</td><td>Condições meteorológicas</td><td>Teto e visibilidade afetam disponibilidade; IFR não é sinônimo de IMC.</td></tr><tr><td>Classe do espaço aéreo</td><td>Acesso e serviços aplicáveis</td><td>A forma de prover separação varia; não basta dizer “há ATC”.</td></tr><tr><td>CNS</td><td>Comunicação, navegação e vigilância</td><td>Equipagem e desempenho precisam sustentar a operação prevista.</td></tr></tbody></table></div>
</Slide>
<Slide kicker="01 • Serviços e coordenação" title="ATC é uma parte dos serviços de tráfego aéreo" minutes={5} source="ICA 100-37, disposições gerais, arts. 88–90 e capítulos de controle, informação de voo e alerta." notes="ATS abrange controle, informação de voo, alerta e o assessoramento onde aplicável. TWR, APP e ACC são órgãos com áreas de responsabilidade próprias: não deduzir o órgão apenas pelo nome do volume. ATFM trata desequilíbrios previstos de demanda e capacidade; separação ATC trata os encontros conforme regras aplicáveis. Exemplo: reduzir partidas por saturação de uma terminal não decide a manobra de cada aeronave.">
<div className="air-bands"><article><h3>ATC • controle</h3><p>TWR, APP e ACC organizam o tráfego em suas responsabilidades e prestam separação conforme a classe e a operação.</p></article><article><h3>FIS e alerta</h3><p>Informação de voo apoia a condução segura; alerta aciona e auxilia os serviços de busca e salvamento.</p></article><article><h3>Gestão do espaço e do fluxo</h3><p>Organizar volumes e ajustar demanda à capacidade são decisões distintas de controlar um encontro entre aeronaves.</p></article><article><h3>Transferência e coordenação</h3><p>Plano, posição e condições de transferência precisam acompanhar a passagem entre áreas de responsabilidade.</p></article></div>
</Slide>
<Slide kicker="01 • Dimensão vertical" title="Altitude e altura mudam a leitura de uma rota" minutes={5} source="ICA 100-12, definições e regras de voo; exemplo didático." notes="Use o exemplo hipotético: terreno 2.500 ft MSL e aeronave 3.000 ft MSL resultam em 500 ft AGL naquele ponto. Se o terreno sobe, AGL diminui. Relacione altitude ao ajuste altimétrico e nível de voo à pressão padrão. Não usar estes valores como alturas mínimas. A separação de obstáculos e as restrições publicadas precisam ser verificadas separadamente.">
<div className="air-altitude"><div><div className="air-level">Aeronave <b>3.000 ft MSL</b></div><div className="air-height">↕ <b>500 ft AGL</b><span>altura acima do terreno local</span></div><div className="air-ground">Terreno <b>2.500 ft MSL</b></div><div className="air-sea">Nível médio do mar • referência MSL</div></div><div className="air-reading"><article><h3>MSL • nível médio do mar</h3><p>Referência usada para comparar altitudes numa mesma base.</p></article>
<article><h3>AGL • acima do terreno</h3><p>Depende da elevação local. O mesmo nível MSL produz alturas AGL diferentes.</p></article>
<article><h3>Exemplo, não parâmetro operacional</h3><p>3.000 ft MSL − 2.500 ft de terreno = 500 ft AGL. Obstáculos exigem avaliação adicional.</p></article></div></div>
</Slide>
<Slide kicker="01 • Planejamento de uma operação" title="Uma carta precisa ser lida junto das regras e restrições" minutes={4} source="ICA 100-12, arts. 3–7, regras gerais e capítulo de voo VFR; ICA 100-37." notes="Explique a diferença entre informação permanente, alterações programadas e informação temporária. Não ensinar a operar usando um mapa de estudo. Exercício oral: um vertiporto parece fora de uma CTR, mas o voo cruza a saída de um aeroporto e uma restrição temporária. Liste o que é preciso consultar antes de avaliar a rota.">
<div className="air-bands"><article><h3>Limites e procedimentos</h3><p>Na AIP e nas cartas: dimensões, classe, rotas, frequências, chegadas e saídas.</p></article><article><h3>Atualização</h3><p>NOTAM e suplementos podem alterar disponibilidade, restrições e condições durante o período do voo.</p></article><article><h3>Operação pretendida</h3><p>Regras de voo, aeronave, equipagem, meteorologia e capacidade de cumprir os procedimentos.</p></article><article><h3>Áreas condicionadas</h3><p>Áreas proibidas, restritas e perigosas têm condições próprias. Não são novas classes ATS.</p></article></div>
</Slide>
<Slide kicker="01 • Leitura aplicada • São Paulo" title="A cidade já compartilha o espaço com aeroportos" minutes={4} source="SIGMA-Sky P2, §2.3, fig. 2.3, p. 16." notes="Identifique áreas sombreadas, aeroportos e concentração de pontos. Diferencie CTR de ATZ: proteção/organização do tráfego não é uma coleção de discos arbitrários. A representação histórica do estudo serve para discutir interfaces. Limites e procedimentos de voo dependem das publicações vigentes. Pergunta: quais coordenações seriam necessárias entre um vertiporto e a CTR?">
<div className="air-evidence"><Media assetId="sigma-ctr" /><div className="air-reading"><article><h3>Leia a figura</h3><p>As zonas dos aeroportos se sobrepõem à região que concentra helipontos e deslocamentos potenciais.</p></article>
<article><h3>CTR e ATZ</h3><p>CTR: espaço aéreo controlado associado ao aeródromo. ATZ: volume destinado à proteção do tráfego de aeródromo.</p></article>
<article><h3>Consequência</h3><p>A rede UAM precisa compatibilizar acesso, chegada, saída e coordenação com o tráfego já organizado.</p></article></div></div>
</Slide>
<Slide kicker="01 • Rotas visuais" title="REH e REA orientam a circulação visual" minutes={4} source="SIGMA-Sky P2, §§2.2 e 4.2, fig. 4.3; concepção de rede do estudo." notes="Leia as cores da legenda. REH é rota especial de helicópteros; REA é rota especial de aeronaves em voo visual. Esta imagem mostra as REH e conexões propostas, não toda a rede REA. Explique referências visuais e procedimentos locais. Não use a figura como carta de navegação. Pergunte por que a reta mais curta não define a rota utilizável.">
<div className="air-evidence"><Media assetId="sigma-rede6" /><div className="air-reading"><article><h3>Estrutura existente</h3><p>REH organiza circulação de helicópteros; REA atende aeronaves em voo visual. Ambas precisam ser consideradas.</p></article>
<article><h3>Leia o traçado</h3><p>Azul e rosa representam REH; laranja mostra rotas/conexões da rede proposta. São camadas diferentes.</p></article>
<article><h3>Decisão de projeto</h3><p>A conexão mais curta pode cruzar um fluxo ou volume incompatível. Distância é apenas um critério.</p></article></div></div>
</Slide>
<Slide kicker="02 • Integração UAM" title="A dificuldade cresce nos encontros e nas interfaces" minutes={5} source="FAA UAM ConOps 2.0; DECEA PCA 351-7; CORUS-XUAM §2.2." notes="Não equiparar aumento de voos automaticamente a aumento de conflitos: geometria, sincronização e desempenho importam. Discuta um cruzamento com duas aeronaves iguais e depois um fluxo misto. No segundo, velocidades e capacidade de manobra diferem. A maior automação proposta depende de informação consistente e responsabilidades claras.">
<div className="air-bands"><article><h3>Concentração espacial</h3><p>Entradas, cruzamentos e vertiportos concentram operações mesmo numa região com baixa ocupação média.</p></article><article><h3>Concentração temporal</h3><p>Picos de demanda e chegadas sincronizadas podem esgotar um recurso antes de saturar a rede inteira.</p></article><article><h3>Desempenho heterogêneo</h3><p>Velocidade, subida, navegação e resposta a desvios variam entre aeronaves e operadores.</p></article><article><h3>Coordenação</h3><p>Novos serviços devem conversar com ATM e com quem já utiliza a região.</p></article></div>
</Slide>
<Slide kicker="02 • Desenho do espaço" title="Rotas livres, camadas e corredores fazem escolhas diferentes" minutes={6} source="FAA UAM ConOps 2.0, §4.4; DECEA PCA 351-7, arts. 75–88; CORUS-XUAM §2.3; Wing et al., 2022." notes="Apresente alternativas de estruturação, não estágios obrigatórios. Trajetórias flexíveis reduzem restrições geométricas, mas requerem coordenação de mais encontros. Corredores podem organizar fluxo e concentrar gargalos. Camadas mudam encontros horizontais sem resolver transições. Pergunte em qual ambiente cada benefício compensaria o custo.">
<div className="air-table-wrap"><table><thead><tr><th>Alternativa</th><th>O que organiza</th><th>Custo ou dependência</th></tr></thead><tbody><tr><td>Trajetórias flexíveis</td><td>Escolha de caminho por operação</td><td>Mais combinações de encontro para coordenar.</td></tr><tr><td>Camadas</td><td>Distribuição vertical dos fluxos</td><td>Subida, descida, terreno e obstáculos continuam críticos.</td></tr><tr><td>Rotas / corredores</td><td>Caminhos e volumes de passagem</td><td>Entradas e cruzamentos podem concentrar demanda.</td></tr><tr><td>Volumes por desempenho</td><td>Condições de acesso e serviços</td><td>Exige demonstrar equipagem, conformidade e capacidade de resposta.</td></tr></tbody></table></div>
</Slide>
<Slide kicker="02 • FAA" title="Corredores UAM articulam uma operação cooperativa" minutes={5} source="FAA UAM ConOps 2.0, §4.4, figura 4." notes="Leia as duas direções e a ligação entre vertiportos. Corredor não é simplesmente um tubo exclusivo para propulsão elétrica. Participantes precisam cumprir desempenho e práticas cooperativas. A FAA apresenta visão futura, não um procedimento operacional já universalmente implantado. Pergunte quem informa o voo a outros operadores.">
<div className="air-evidence"><Media assetId="faa-2023-uam-corridor-concept" /><div className="air-reading"><article><h3>Volume + participação</h3><p>A geometria organiza o espaço; práticas cooperativas e requisitos organizam quem pode utilizá-lo.</p></article>
<article><h3>Intenção compartilhada</h3><p>Rotas, tempos e restrições precisam estar disponíveis aos serviços e operadores envolvidos.</p></article>
<article><h3>Evolução gradual</h3><p>Operações iniciais usam o ambiente existente; a concepção explora coordenação para maior densidade.</p></article></div></div>
</Slide>
<Slide kicker="02 • DECEA" title="Volumes UAM devem se integrar ao SISCEAB" minutes={5} source="DECEA PCA 351-7, fig. 1 e arts. 26–28, 75–84." notes="Leia a figura original e a associação dos ambientes. No contexto desta concepção, 400 ft AGL descreve UTM; o próprio texto prevê interseção UTM/UAM. Explique que aeronaves UAM cruzam interfaces nas chegadas e partidas. Informação compartilhada é necessária. Não generalizar um limite global para qualquer operação de drones.">
<div className="air-evidence"><Media assetId="decea-ambientes" /><div className="air-reading"><article><h3>Estruturas preservadas</h3><p>FIR, CTA, CTR e ATZ continuam compondo o sistema. A UAM precisa integrar-se ao SISCEAB.</p></article>
<article><h3>Interseção prevista</h3><p>O texto adota até 400 ft AGL para o ambiente UTM e reconhece interseção com UAM.</p></article>
<article><h3>Condição de integração</h3><p>Compartilhar informações e estabelecer requisitos de acesso e desempenho para cada volume.</p></article></div></div>
</Slide>
<Slide kicker="02 • Europa • CORUS-XUAM" title="O plano de voo pode ser uma sequência de volumes 4D" minutes={6} source="CORUS-XUAM, edição 4, §3.5.2.2.1, figura 10, p. 61." notes="Explique o U-plan: volumes tridimensionais com janelas de entrada e saída. A figura distingue permanência numa área e deslocamento ao longo de um caminho. Linhas azuis só ilustram intenção: o plano contém volumes. O documento prevê serviços por ambiente X/Y/Z: não são classes ATS A–G. Diferenciar a proposta completa de serviços daquilo que está implantado em cada Estado.">
<div className="air-wide-evidence"><Media assetId="corus-2023-volumes4d" /><div className="air-three"><article><h3>Espaço + tempo</h3><p>Cada volume tem limites espaciais e uma janela de ocupação.</p></article><article><h3>Incerteza explícita</h3><p>Posição, relógio, vento e decolagem alteram a previsão de passagem.</p></article><article><h3>Serviços conectados</h3><p>Autorização, previsão de conflito e monitoramento usam o mesmo plano.</p></article></div></div>
</Slide>
<Slide kicker="02 • Comparação dos CONOPS" title="Os CONOPS aproximam serviços, mas diferem na organização" minutes={5} source="FAA 2023, §4.4; DECEA 2024, arts. 73–88; CORUS-XUAM 2023, §§2.3 e 3.5." notes="Não apresentar equivalência jurídica entre PSU, USSP e órgãos ATS. Compare três dimensões comuns e peça que a turma identifique a diferença na organização espacial. Os documentos são versões de concepção, não prova de implantação. O serviço de cada operação depende de regras e aprovações aplicáveis.">
<div className="air-table-wrap"><table><thead><tr><th>Dimensão</th><th>FAA</th><th>DECEA</th><th>CORUS-XUAM</th></tr></thead><tbody><tr><td>Estrutura</td><td>Corredores UAM e operações cooperativas</td><td>Volumes UAM e acesso por desempenho</td><td>Volumes de serviço e planos 4D</td></tr><tr><td>Coordenação</td><td>Operadores, PSU e regras cooperativas</td><td>SISCEAB, provedores e interfaces ATM</td><td>USSP, serviços U-space e interface ATM</td></tr><tr><td>Dependência comum</td><td>Compartilhar intenção</td><td>Compatibilizar responsabilidades</td><td>Monitorar conformidade</td></tr><tr><td>Questão de projeto</td><td>Como entrar e sair?</td><td>Como coexistir com o tráfego atual?</td><td>Como manter planos compatíveis?</td></tr></tbody></table></div>
</Slide>
<Slide kicker="Intervalo" title="Do desenho do espaço à coordenação dos voos" minutes={10} source="Retomada didática." notes="Faça uma pausa de dez minutos. Na volta, retome a diferença entre desenhar um volume e atribuir seu uso no tempo. As próximas seções examinam serviços, algoritmos e evidências.">
<div className="air-bands"><article><h3>O espaço</h3><p>Limites, classes, rotas e volumes organizam onde a operação pode ocorrer.</p></article><article><h3>O acesso</h3><p>Regras e desempenho definem quais operações podem utilizar cada ambiente.</p></article><article><h3>A pergunta que fica</h3><p>Dois operadores pedem o mesmo recurso no mesmo horário. Como resolver?</p></article><article><h3>Depois da pausa</h3><p>Serviços cooperativos, capacidade, conflitos e avaliação das alternativas.</p></article></div>
</Slide>
<Slide kicker="03 • Literatura • Wing et al. (2022)" title="Digital Flight propõe ampliar a cooperação entre operações" minutes={4} source="Wing et al. Digital Flight, NASA/TM–20220013225, §§1.1, 2 e 3." notes="Deixe claro que Digital Flight/DFR é uma proposta de modo complementar. Não é regra brasileira vigente nem autorização para voo autônomo. A responsabilidade do operador por separação, sustentada por automação e cooperação, é elemento central. O relatório explora integração com VFR/IFR e acesso baseado em desempenho; implementação exige padrões e validação.">
<div className="air-bands"><article><h3>Ideia central</h3><p>Usar informação digital, automação e práticas cooperativas para ampliar acesso e flexibilidade.</p></article><article><h3>Responsabilidade</h3><p>Na proposta, o operador assume a segurança da trajetória, incluindo separação, com suporte tecnológico.</p></article><article><h3>Coexistência</h3><p>O objetivo é integrar operações com VFR e IFR, incluindo usuários novos e existentes.</p></article><article><h3>Condição para avançar</h3><p>Requisitos de desempenho, regras de cooperação e demonstração de segurança precisam ser estabelecidos.</p></article></div>
</Slide>
<Slide kicker="03 • Gestão de conflitos" title="Planejamento, separação e prevenção de colisão se complementam" minutes={6} source="Lee et al. 2022, introdução; Wing et al. 2022, §3; CORUS-XUAM §§3.5 e 3.14." notes="Descreva três camadas e não três algoritmos equivalentes. DCB e desconflito pré-voo reduzem situações de encontro; separação lida com encontros remanescentes segundo responsabilidades; prevenção de colisão é última barreira. Uma reserva estratégica não garante execução. Exemplo: atraso muda passagem pelo cruzamento e exige atualizar previsão.">
<div className="air-comparison"><article><h3>1 • Gestão estratégica</h3><p>Antes do encontro: compatibilizar planos, demanda e capacidade.</p><p>Exemplo: reprogramar a partida.</p></article><article><h3>2 • Provisão de separação</h3><p>Durante a operação: detectar e resolver encontros remanescentes.</p><p>Exemplo: ajustar uma trajetória.</p></article><article><h3>3 • Prevenção de colisão</h3><p>Última barreira quando as anteriores não bastaram.</p><p>Não deve sustentar a capacidade planejada.</p></article></div>
</Slide>
<Slide kicker="03 • Atores e informação" title="O plano de voo precisa circular entre atores" minutes={4} source="NASA, Provider of Services to UAM (2021); FAA 2023; DECEA PCA 351-7, arts. 73–74." notes="Defina intenção operacional: onde e quando pretende voar. PSU apoia intercâmbio e coordenação; não substitui automaticamente ATC, operador ou piloto. Separe plano, aceitação/coordenação e execução. Conecte com disponibilidade do vertiporto. Exemplo: destino sem capacidade demanda ajuste antes da partida.">
<div className="air-bands"><article><h3>Operador e piloto</h3><p>Propõem a operação, cumprem os requisitos e executam o voo dentro das responsabilidades aplicáveis.</p></article>
<article><h3>PSU • serviços UAM</h3><p>Apoia intercâmbio de intenção, restrições, coordenação e monitoramento, conforme a concepção adotada.</p></article>
<article><h3>Vertiporto</h3><p>Informa disponibilidade de infraestrutura e recursos que condicionam chegada e saída.</p></article>
<article><h3>ATM / ATC</h3><p>Mantém as responsabilidades aplicáveis e coordena as interfaces com o tráfego convencional.</p></article></div>
</Slide>
<Slide kicker="03 • Pesquisa • Lee et al. (2022)" title="Capacidade média disponível pode esconder picos locais" minutes={7} source="Lee et al. 2022, §III.B, figura 6, PDF p. 5. DOI 10.1109/DASC55683.2022.9925753." notes="O artigo completo usa 60 voos, cinco vertiportos e quatro operações por janela de 12 minutos. Não usar os números do resumo preliminar, que são diferentes. Leia DF100/bin4: demanda original de sete para capacidade quatro. O método desloca partidas e respeita limites de origem e destino. No cenário ilustrado, 15 voos sofrem atraso, com média 7,1 min entre atrasados. Resultado de simulação sob hipóteses, não capacidade certificada.">
<div className="air-research"><div className="air-pair"><div><h3>Demanda original</h3><Media assetId="lee-2022-demanda-original" /></div><div><h3>Após reprogramação</h3><Media assetId="lee-2022-demanda-ajustada" /></div></div><div className="air-three"><article><h3>Cenário simulado</h3><p>60 voos; 5 vertiportos; limite de 4 operações por janela de 12 minutos.</p></article><article><h3>Resultado</h3><p>O ajuste elimina excessos nas janelas planejadas e transfere custo para o atraso no solo.</p></article><article><h3>Limite</h3><p>Não demonstra separação entre todos os pares em voo; incertezas ainda afetam a execução.</p></article></div></div>
</Slide>
<Slide kicker="03 • Exemplo de capacidade" title="Atrasar no solo pode evitar saturação de um recurso" minutes={5} source="Exemplo didático inspirado no problema de DCB; Lee et al. 2022." notes="Os valores 12/8/4 são um exemplo didático independente dos dados do artigo. Doze entradas para oito posições exigem ao menos quatro reprogramações nessa janela. O cálculo agregado não verifica simultaneidade dentro da janela nem separação de pares. Conecte a granularidade temporal da capacidade ao número de intervenções táticas.">
<div className="air-example"><div className="air-equation"><div><b>12</b><span>entradas pretendidas</span></div><div><b>8</b><span>capacidade por janela</span></div><div><b>4</b><span>partidas reprogramadas</span></div></div><p className="air-example-label">Exemplo didático • um recurso • janela de 10 minutos</p><div className="air-three"><article><h3>Recurso</h3><p>Um waypoint, setor ou vertiporto tem limite por intervalo de tempo.</p></article>
<article><h3>Decisão estratégica</h3><p>Redistribuir partidas para que a ocupação planejada caiba na capacidade.</p></article>
<article><h3>O que medir</h3><p>Atraso no solo, vazão, fila, equidade e conflitos remanescentes.</p></article></div></div>
</Slide>
<Slide kicker="03 • Desconflito estratégico" title="Desconflitar exige comparar lugar e tempo" minutes={6} source="CORUS-XUAM, §3.5.2; exemplo didático de trajetórias 4D." notes="Dois voos atravessam X às 10:05: pode haver conflito segundo o volume de proteção adotado. Deslocar partida B para 10:02 altera passagem para 10:07 neste exemplo. Dois minutos não são mínimo operacional: ilustram mudança temporal. Recalcular o restante da rede para não transferir o conflito. Vento/partida incerta mudam previsão.">
<div className="air-example"><table><thead><tr><th>Plano</th><th>Partida</th><th>Passagem em X</th><th>Decisão</th></tr></thead><tbody><tr><td>Voo A</td><td>10:00</td><td>10:05</td><td>Manter</td></tr><tr><td>Voo B • original</td><td>10:00</td><td>10:05</td><td>Reavaliar ocupação simultânea</td></tr><tr><td>Voo B • ajustado</td><td>10:02</td><td>10:07</td><td>Verificar novamente toda a trajetória</td></tr></tbody></table><p className="air-example-label">Tempos ilustrativos • não representam mínimo de separação</p><div className="air-three"><article><h3>Antes</h3><p>A e B planejam ocupar o mesmo ponto X às 10:05.</p></article>
<article><h3>Replanejar</h3><p>Ajustar a partida de B desloca sua passagem por X; verificar todos os demais recursos.</p></article>
<article><h3>Durante o voo</h3><p>Desvios de horário e trajetória exigem atualização e mecanismos de resposta.</p></article></div></div>
</Slide>
<Slide kicker="03 • Pesquisa • Seuken et al. (2022)" title="Quem reserva primeiro deve ficar com todo o espaço?" minutes={6} source="Seuken et al. Market Design for Drone Traffic Management, AAAI 2022, §§2–4. DOI 10.1609/aaai.v36i11.21493." notes="Artigo conceitual sobre UTM: não trata de ensaio com passageiros eVTOL. Os autores discutem eficiência, equidade, simplicidade, incentivos e escalabilidade. Exemplo didático: reserva antecipada gratuita pode estimular bloqueio de horários que não serão usados. Não concluir que leilão é a solução: diferentes mecanismos têm diferentes incentivos e custos. Peça uma regra de cancelamento e seu possível efeito adverso.">
<div className="air-bands"><article><h3>Problema</h3><p>Quando o recurso é escasso, a regra de acesso influencia o comportamento dos operadores.</p></article><article><h3>Exemplo</h3><p>Reservas gratuitas e canceláveis podem incentivar pedidos antecipados além da necessidade real.</p></article><article><h3>Critérios do artigo</h3><p>Eficiência, equidade, simplicidade, resistência à manipulação e escalabilidade.</p></article><article><h3>Aplicação à UAM</h3><p>Definir prioridade, cancelamento e uso de slots faz parte do projeto operacional, além da geometria.</p></article></div>
</Slide>
<Slide kicker="03 • Separação e CNS" title="Mais precisão de navegação não resolve tudo" minutes={5} source="Wing et al. 2022, §3.3; ICA 100-37, serviços de vigilância e separação; DECEA PCA 351-7." notes="RNP inclui monitoramento e alerta, mas não fixa sozinha a separação entre aeronaves. Relacione erro de posição, latência, atualização e tempo de resposta. Não apresentar um mínimo universal UAM. A margem depende do encontro, do ambiente e da demonstração de segurança. Discuta por que posição muito precisa recebida tarde ainda pode ser inadequada.">
<div className="air-table-wrap"><table><thead><tr><th>Capacidade</th><th>Pergunta operacional</th><th>Efeito no projeto</th></tr></thead><tbody><tr><td>Comunicação</td><td>A informação chega a tempo e sem interrupção?</td><td>Latência e falhas afetam coordenação e resposta.</td></tr><tr><td>Navegação</td><td>A aeronave permanece no volume previsto?</td><td>Erro, integridade e alerta condicionam a conformidade.</td></tr><tr><td>Vigilância</td><td>O sistema observa os demais usuários?</td><td>Cobertura e atualização afetam previsão dos encontros.</td></tr><tr><td>Resposta</td><td>Quem decide e executa a mudança?</td><td>Tempo de reação e desempenho precisam caber nas margens.</td></tr></tbody></table></div>
</Slide>
<Slide kicker="03 • Contingências" title="Uma rota bloqueada redistribui problemas pela rede" minutes={5} source="CORUS-XUAM, §§2.2.3–2.2.4 e 3.12; Lee et al. 2022, §IV." notes="Trabalhe um bloqueio e uma mudança de horário. Identifique quem está no solo e quem já voa, recursos alternativos e autoridade pela decisão. Energia e desempenho limitam alternativas. Peça que a turma diga qual informação precisa mudar no plano compartilhado e como confirmar que todos receberam a atualização.">
<div className="air-bands"><article><h3>Bloqueio de área</h3><p>Uma restrição temporária pode inviabilizar o caminho planejado e concentrar fluxo numa alternativa.</p></article>
<article><h3>Incerteza de execução</h3><p>Atraso de partida, vento e variação do tempo de voo alteram a ocupação prevista dos recursos.</p></article>
<article><h3>Resposta coordenada</h3><p>Atualizar intenções, reavaliar capacidade, reter partidas e tratar aeronaves já em voo.</p></article>
<article><h3>Critério de robustez</h3><p>Medir conflitos, atraso, cancelamentos e recuperação da rede sob perturbação.</p></article></div>
</Slide>
<Slide kicker="04 • Aplicação • SIGMA-Sky / RMSP" title="Compartilhar rotas ou dedicar corredores?" minutes={5} source="SIGMA-Sky Produto 2, figuras 5.5(a) e 5.7(a)." notes="Agora utilize o estudo local para aplicar o quadro conceitual da aula. Esquerda: compartilhamento de REH. Direita: corredor dedicado em análise. Compare interfaces, extensão do trajeto, ocupação e necessidade de serviços. As geometrias são propostas de pesquisa; não afirmar aprovação ou desempenho superior. Não detalhar os cenários C1–C10.">
<div className="air-research"><div className="air-pair"><div><h3>Compartilhar a estrutura existente</h3><Media assetId="sigma-compartilhada" /></div><div><h3>Propor estrutura dedicada</h3><Media assetId="sigma-dedicada2d" /></div></div><div className="air-three"><article><h3>Tráfego misto</h3><p>Velocidades e entradas distintas continuam exigindo coordenação.</p></article><article><h3>Interfaces</h3><p>Um corredor dedicado ainda precisa conectar solo, rotas e outros volumes.</p></article><article><h3>Comparação</h3><p>Usar a mesma demanda e critérios para avaliar as duas alternativas.</p></article></div></div>
</Slide>
<Slide kicker="04 • Aplicação • SIGMA-Sky / RMSP" title="A compatibilidade precisa ser examinada em três dimensões" minutes={5} source="SIGMA-Sky P2, fig. 5.11, p. 59; §5.1.2.2." notes="As superfícies nesta análise foram construídas a partir de trajetórias observadas, percentis e suavização. Não confundir com superfícies normativas de proteção de obstáculos. Mostre que o próprio Produto 2 limita a conclusão à aderência espacial preliminar. Pergunte como variações de pista e meteorologia poderiam alterar o resultado.">
<div className="air-dual"><div><Media assetId="sigma-aeroportos2d" /><Media assetId="sigma-aeroportos3d" /></div><div className="air-reading"><article><h3>Camada adicional</h3><p>Os fluxos de chegada e saída de aeroportos ocupam volumes além das redes REH/REA.</p></article>
<article><h3>Natureza da figura</h3><p>Envelopes construídos a partir de trajetórias do estudo; não são uma carta operacional.</p></article>
<article><h3>Limite da conclusão</h3><p>Compatibilidade geométrica preliminar ainda exige simulação e avaliação operacional.</p></article></div></div>
</Slide>
<Slide kicker="04 • Avaliação" title="Uma solução só melhora se o critério estiver declarado" minutes={5} source="Lee et al. 2022; Seuken et al. 2022; CORUS-XUAM; síntese didática." notes="Compare resultados de simulação e critérios de projeto. Perda de separação é indicador, não prova isolada de certificação. Acrescente equidade na distribuição de atrasos. Mantenha demanda e desempenho iguais quando comparar geometrias; altere uma hipótese por vez e repita com perturbações. Exija que o aluno identifique um trade-off.">
<div className="air-table-wrap"><table><thead><tr><th>Critério</th><th>Indicador possível</th><th>Pergunta de comparação</th></tr></thead><tbody><tr><td>Segurança</td><td>Conflitos / perdas de separação</td><td>Em qual demanda e com qual incerteza aparecem?</td></tr><tr><td>Eficiência</td><td>Atraso, distância e tempo de voo</td><td>Onde o custo da coordenação foi absorvido?</td></tr><tr><td>Capacidade</td><td>Voos processados por intervalo</td><td>Qual recurso limita a vazão e como cresce a fila?</td></tr><tr><td>Resiliência</td><td>Recuperação e voos afetados</td><td>O que acontece quando uma rota fica indisponível?</td></tr></tbody></table></div>
</Slide>
<Slide kicker="04 • Oficina" title="Projete uma ligação e explique como ela funcionaria" minutes={20} source="Atividade E06: aplicação dos conceitos da aula." notes="Grupos de 3–4. Distribua 3 min para escolher caso, 7 para desenho, 5 para coordenação e 5 para contingência. Ofereça dois casos: ligação aeroporto-centro com interface de espaço controlado ou ligação entre bairros com tráfego visual. Entrega em uma folha: esquema com legenda, três hipóteses e resposta a bloqueio. Não exigir coordenadas ou mínimos operacionais.">
<div className="air-bands"><article><h3>Escolha o contexto</h3><p>Aeroporto–centro ou ligação entre bairros. Declare tráfego existente, terreno e restrições relevantes.</p></article><article><h3>Desenhe a estrutura</h3><p>Mostre origem, destino, rotas, volumes e pontos onde diferentes fluxos se encontram.</p></article><article><h3>Defina a operação</h3><p>Indique regra de voo, serviço necessário, recurso limitante e forma de compatibilizar horários.</p></article><article><h3>Teste uma perturbação</h3><p>Bloqueie um trecho e explique a resposta para aeronaves no solo e em voo.</p></article></div>
</Slide>
<Slide kicker="Discussão e síntese" title="Uma boa proposta conecta espaço, regras e evidência" minutes={10} source="Síntese E06." notes="Reserve cerca de oito minutos para relatos e dois para fechar. Cada grupo apresenta uma decisão e como a testaria. Resposta esperada liga desenho a classe, serviço, capacidade e contingência. Retome a capa: o objeto da aula é organizar o uso do espaço aéreo. Conecte com a aula de vertiportos: capacidade de solo condiciona a rede.">
<div className="air-bands"><article><h3>Estrutura</h3><p>O desenho mostra onde a operação se encaixa e quais interfaces precisam ser tratadas.</p></article><article><h3>Responsabilidade</h3><p>A classe, a regra de voo e os serviços explicam quem informa, coordena e separa.</p></article><article><h3>Evidência</h3><p>A proposta declara hipótese, indicador e uma condição capaz de revelar sua limitação.</p></article><article><h3>Para levar adiante</h3><p>Capacidade de espaço aéreo, vertiporto e coordenação precisam ser estudadas em conjunto.</p></article></div>
</Slide>
<Slide kicker="Bibliografia e downloads" title="Normas e conceitos operacionais" minutes={0} source="Biblioteca E06." notes="Documentos completos disponíveis localmente na biblioteca. Normas: ICA 100-12 edição 2024 e ICA 100-37 compilada com alteração em vigor em 27/11/2025. CONOPS: FAA v2.0, PCA 351-7 e CORUS edição 4. Todos são versões identificadas, e não afirmação de implantação universal.">
<ReadingList ids={['decea-2024-ica10012','decea-2025-ica10037','faa-2023-uam-conops-2','decea-2024-conops-uam-nacional','corus-2023-conops4']} />
</Slide>
<Slide kicker="Bibliografia e downloads" title="Pesquisas e estudo de caso" minutes={0} source="Biblioteca E06 e créditos das figuras." notes="Lee et al. e Seuken et al. foram localizados a partir dos Produtos 2 e 1, respectivamente. Wing et al. e os CONOPS são fontes primárias discutidas no Produto 1. SIGMA-Sky é fonte de síntese e do caso RMSP. Créditos completos por figura e slide estão na página de materiais.">
<ReadingList ids={['lee-2022-dcb-vertiports','seuken-2022-market-design','nasa-2022-digital-flight','nasa-2021-provider-services-uam','sigmasky-produto1','sigmasky-produto2']} />
</Slide>
</PresentationDeck>;
}
